"""empty message

Revision ID: f5a31a7498f4
Revises: 
Create Date: 2021-11-07 18:51:52.147697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a31a7498f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create', sa.DateTime(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_cash'), 'productions', ['cash'], unique=False)
    op.create_index(op.f('ix_productions_create'), 'productions', ['create'], unique=True)
    op.create_index(op.f('ix_productions_description'), 'productions', ['description'], unique=False)
    op.create_index(op.f('ix_productions_image'), 'productions', ['image'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_cpf'), 'user', ['cpf'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_street'), 'user', ['street'], unique=True)
    op.create_table('wish_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('production', sa.Text(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('create', sa.DateTime(), nullable=False),
    sa.Column('payment', sa.Text(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user'),
    sa.UniqueConstraint('production')
    )
    op.create_index(op.f('ix_wish_list_cash'), 'wish_list', ['cash'], unique=True)
    op.create_index(op.f('ix_wish_list_payment'), 'wish_list', ['payment'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wish_list_payment'), table_name='wish_list')
    op.drop_index(op.f('ix_wish_list_cash'), table_name='wish_list')
    op.drop_table('wish_list')
    op.drop_index(op.f('ix_user_street'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cpf'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_productions_image'), table_name='productions')
    op.drop_index(op.f('ix_productions_description'), table_name='productions')
    op.drop_index(op.f('ix_productions_create'), table_name='productions')
    op.drop_index(op.f('ix_productions_cash'), table_name='productions')
    op.drop_table('productions')
    op.drop_table('category')
    # ### end Alembic commands ###
